import { prisma } from "@/lib/db";
import { generateEmbedding } from "@/lib/ai/embeddings";
import { getCurrentVersion } from "@/lib/utils";
import type { Asset, Collection } from "@/types";

/**
 * Stage 4.1 — Search indexing.
 *
 * Builds and persists the two retrieval signals consumed by the hybrid search
 * in `lib/server/queries.ts` (`hybridSearchAssets`):
 *   1. A pgvector `vector(1536)` embedding derived from the denormalized
 *      `searchText` — generated by `@/lib/ai/embeddings` (OpenAI text-embedding
 *      -3-small → Gemini gemini-embedding-001 → deterministic local fallback).
 *   2. A `searchText` string over which PostgreSQL full-text search runs
 *      (`to_tsvector` / `plainto_tsquery`).
 *
 * The vector column is mapped with `Unsupported("vector(1536)")` in the Prisma
 * schema, so it is never exposed through the typed client; all vector reads and
 * writes go through raw SQL here.
 */

/**
 * Denormalized searchable text for an asset. This is what both full-text search
 * and (together with the query text) embeddings are derived from, so keeping the
 * sources consistent matters: FTS matches tokens, the embedding captures meaning.
 */
export function buildSearchText(asset: Asset, collectionName?: string): string {
  const version = getCurrentVersion(asset);
  const parts = [
    asset.name,
    version.metadata.title,
    version.metadata.description,
    version.metadata.prompt,
    version.metadata.generator,
    asset.tags.join(" "),
    collectionName,
    asset.usageNotes,
    asset.type,
    asset.status,
  ];
  return parts
    .filter((p): p is string => Boolean(p && p.trim().length > 0))
    .join("\n")
    .normalize("NFKC")
    .toLowerCase();
}

/**
 * Computes and persists the search index (embedding + searchText) for a single
 * asset. `searchText` is written through the typed client; the vector embedding
 * through raw SQL because the `Unsupported("vector(1536)")` column is not exposed
 * by the client types. Safe to call on newly created or updated assets.
 */
export async function indexAsset(asset: Asset, collectionName?: string): Promise<void> {
  const searchText = buildSearchText(asset, collectionName);
  const embedding = await generateEmbedding(searchText);

  await prisma.asset.update({
    where: { id: asset.id },
    data: { searchText },
  });

  const vectorLiteral = `[${embedding.join(",")}]`;
  await prisma.$executeRaw`
    UPDATE "Asset" SET "embedding" = ${vectorLiteral}::vector
    WHERE "id" = ${asset.id}
  `;
}

/** Indexes a full inventory of assets (used by the demo seed/reset path). */
export async function indexCollection(assets: Asset[], collections: Collection[]): Promise<void> {
  for (const asset of assets) {
    const collection = collections.find((c) => c.id === asset.collectionId);
    await indexAsset(asset, collection?.name);
  }
}